#!/bin/bash

root=~/git/server.dns
url="https://abc.com"

. ${root}/script/user.sh
script=${root}/script/afterConnected.sh

pidfile="/tmp/openconnect-pid"

case "$1" in
start)
    sleep 8
    echo "$password" | openconnect -b --pid-file=$pidfile --user=$username --script=${script} $url
    ;;
stop)
    cat $pidfile  | xargs kill -2
    ;;
*)
    echo "$0 <start|stop>"
    exit 1
esac