#!/bin/sh

root=/root/git/server.dns
url="https://abc.com:8443"

pidfile="/tmp/openconnect-pid"

case "$1" in
start)
    sleep 8
	. ${root}/script/user.sh
	script=${root}/script/afterConnected.sh
    echo "${ocpass}" | openconnect -b --pid-file=$pidfile --user=${ocuser} --script=${script} $url
    ;;
stop)
    cat $pidfile  | xargs kill -2
    ;;
*)
    echo "$0 <start|stop>"
    exit 1
esac